# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'FinalAssessmentAug16IOS' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
	pod 'Firebase/Core'
	pod 'Firebase/Auth'
	pod 'Firebase/Database'
	pod 'Firebase/Storage'
  # Pods for FinalAssessmentAug16IOS

end
